name: Build sParking with Samba Qt Installer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Samba Client
      run: |
        sudo apt-get update
        sudo apt-get install -y smbclient

    - name: Download Qt Installer from Samba Share
      run: |
        smbclient //10.10.141.46/share -U ${{ secrets.SMB_USERNAME }}%${{ secrets.SMB_PASSWORD }} -c 'get qt-opensource-linux-x64-5.14.2.run' -d 3`

    - name: Make Qt Installer Executable
      run: chmod +x qt-opensource-linux-x64-5.14.2.run

    - name: Install Qt from .run file
      run: |
        ./qt-opensource-linux-x64-5.14.2.run --script qt-installer-noninteractive.qs

    - name: Set up Qt environment
      run: |
        echo 'export PATH=$HOME/Qt/5.14.2/gcc_64/bin:$PATH' >> $HOME/.bashrc
        source $HOME/.bashrc

    - name: Build sParking with qmake and make
      run: |
        cd sParking
        qmake
        make
