name: Build and Run test about sParking with Google Cloud Storage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build sParking with qmake and make
      run: |
        cd sParking
        qmake
        make
