name: Build sParking with Local Qt Installer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Qt from Local .run file
      run: |
        chmod +x qt-opensource-linux-x64-5.14.2.run
        qt-opensource-linux-x64-5.14.2r.run --script qt-installer-noninteractive.qs

    - name: Set up Qt environment
      run: |
        echo 'export PATH=$HOME/Qt/5.14.2/gcc_64/bin:$PATH' >> $HOME/.bashrc
        source $HOME/.bashrc

    - name: Build sParking with qmake and make
      run: |
        cd sParking
        qmake
        make
